name: Build and Deploy to AWS EC2

on:
  push:
    branches:
      - develop  # adjust if you deploy from a different branch v1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'  # use your desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      # Copy the built files and server code to the EC2 instance using scp.
      - name: Copy files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: ${{ secrets.EC2_PORT || 22 }}  # default SSH port is 22
          source: "."
          target: "/home/${{ secrets.EC2_USERNAME }}/form-app"  # adjust target path as needed

      # Execute remote commands via SSH to install dependencies and restart the app.
      - name: Execute remote SSH commands on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: ${{ secrets.EC2_PORT || 22 }}
          script: |
            cd ~/form-app
            # Install Node.js if not present (for Amazon Linux 2)
            if ! command -v node &> /dev/null; then
              curl -fsSL https://rpm.nodesource.com/setup_18.x | sudo bash -
              sudo yum install -y nodejs
            fi
            # Install PM2 globally if not present
            if ! command -v pm2 &> /dev/null; then
              sudo npm install -g pm2
            fi
            # Install project dependencies
            npm install
            # Setup PM2 to start on boot (only run once)
            sudo pm2 startup systemd -u $USER --hp /home/$USER || true
            # Restart or start the application with PM2
            pm2 restart form-app || pm2 start server.js --name form-app
            # Save PM2 configuration
            pm2 save