name: Build and Deploy to AWS EC2

on:
  push:
    branches:
      - develop  # deploy from develop branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'  # use your desired Node.js version

      - name: Install dependencies
        run: npm ci  # usa npm ci para builds más rápidos y confiables

      - name: Build the project
        run: npm run build

      # Copy the built files and server code to the EC2 instance using scp.
      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.7  # usar versión específica más estable
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: ${{ secrets.EC2_PORT || 22 }}
          source: "."
          target: "/home/${{ secrets.EC2_USERNAME }}/form-app"
          debug: true  # habilitar debug para más información
          strip_components: 0

      # Execute remote commands via SSH to install dependencies and restart the app.
      - name: Execute remote SSH commands on EC2
        uses: appleboy/ssh-action@v1.0.3  # usar versión específica más estable
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: ${{ secrets.EC2_PORT || 22 }}
          debug: true  # habilitar debug para más información
          script: |
            cd ~/form-app
            # Verificar que Node.js y PM2 estén disponibles
            echo "Node.js version: $(node --version)"
            echo "PM2 version: $(pm2 --version)"
            # Install project dependencies (production only)
            npm ci --omit=dev
            # Stop the app gracefully if it's running
            pm2 stop form-app || true
            # Start the application with PM2
            pm2 start server.js --name form-app --update-env
            # Save PM2 configuration
            pm2 save
            # Show PM2 status
            pm2 list